#!/usr/bin/env python3
"""docs/main190_new_regions.md: every land region not in base 190E, grouped by area and province, with on-screen name,
capital flag (region_to_province_junctions.is_capital) and the primary / secondary slot templates of the
3k_main_campaign_map start pos (db_out = the DB packed into !!190_expanded_region_test_main190.pack)."""
import collections, re, sys
from pathlib import Path
HERE = Path(__file__).parent
for p in (HERE, HERE.parent / "guandu", HERE.parent): sys.path.insert(0, str(p))
import hexmap
ORIG_HEX = r"Z:/Claude/TerryClone/output/backups/main190_originals_20260929_130639/190Expanded_map.hex"
OUT = Path(r"Z:/Claude/TerryClone/docs/main190_new_regions.md")
AREAS = {"central": "Central Plains", "south": "South", "nomad": "Steppe", "hexi": "Hexi", "region": "Korea / 190E areas"}


def rows(p):
    for l in open(p, encoding="utf-8"):
        if not l.startswith("#"): yield l.rstrip("\n").split("\t")


def nice(t):
    if t is None: return "—"
    if t == "3k_city": return "City (capital)"
    if t == "3k_districts": return "Districts"
    m = re.match(r"3k_resource_(\w+?)_(.*)", t)
    return f"{m.group(2).replace('_', ' ').title()} ({m.group(1)})" if m else t


def main():
    E = set(hexmap.load(ORIG_HEX)["lists"]["land_regions"])
    new = [r for r in hexmap.load(str(HERE / "hex" / "map.hex"))["lists"]["land_regions"] if r not in E and "non_playable" not in r]
    J = {a[1]: (a[0], a[2] == "true") for a in rows(HERE / "db_out/db/region_to_province_junctions_tables/data__.tsv") if a[0] != "province"}
    loc = {}
    for f in ("regions.loc.tsv", "provinces.loc.tsv"):
        for a in rows(HERE / "db_out/text/db" / f):
            if len(a) >= 2: loc[a[0]] = a[1]
    slot = collections.defaultdict(dict)
    for a in rows(HERE / "db_out/db/start_pos_region_slot_templates_tables/data_3k_main_campaign_map.tsv"):
        if a[0] != "campaign": slot[a[2]][a[4]] = a[3]
    prov = collections.defaultdict(list)
    for r in new:
        p, cap = J.get(r, ("(no province)", False))
        prov[p].append((not cap, loc.get("regions_onscreen_" + r, r), r, cap, slot[r].get("primary"), slot[r].get("secondary")))
    pname = lambda p: loc.get("provinces_onscreen_" + p, p)
    groups = collections.defaultdict(list)
    for p, lst in prov.items():
        groups[collections.Counter(AREAS.get(x[2].split("_")[1], "Other") for x in lst).most_common(1)[0][0]].append(p)
    L = ["# 190 Expanded x1.5: new regions", "",
         f"{len(new)} land regions that are not in base 190E (190E has 240, vanilla 201; now {len(new) + 240}). Grouped by province, capital first.",
         "Resource = the region's primary building template in the 3k_main_campaign_map start pos (`start_pos_region_slot_templates`); "
         "capital = `is_capital` in `region_to_province_junctions`. Names are the on-screen names from the pack loc. "
         "Provinces marked *(existing)* are 190E / vanilla provinces that gained a region. Resources re-themed 2026-10-04 "
         "(resource_retheme_190.py: 190 AD history, horses trimmed, silk only on the Silk Road).", "",
         "Source: research/main190/db_out (the DB packed into !!190_expanded_region_test_main190.pack), map.hex for the region list. "
         "Generated by research/main190/new_regions_doc.py.", ""]
    cnt = collections.Counter()
    for a in ["Central Plains", "South", "Steppe", "Hexi", "Korea / 190E areas", "Other"]:
        if a not in groups: continue
        ps = sorted(groups[a], key=pname)
        L += [f"## {a} ({sum(len(prov[p]) for p in ps)} regions, {len(ps)} provinces)", "",
              "| Province | Region | Key | Capital | Primary (resource / city) | Secondary (province flavour) |", "|---|---|---|---|---|---|"]
        for p in ps:
            existing = any(r in E for r, (pp, _) in J.items() if pp == p)
            pn = f"{pname(p)}{' *(existing)*' if existing else ''}<br>`{p}`"
            for i, (_, nm, key, cap, pri, sec) in enumerate(sorted(prov[p])):
                L.append(f"| {pn if i == 0 else ''} | {nm} | `{key}` | {'**Yes**' if cap else ''} | {nice(pri)} | {nice(sec)} |")
                cnt[nice(pri)] += 1
        L.append("")
    L += ["## Totals by primary building", "", "| Primary | Regions |", "|---|---|"] + [f"| {k} | {v} |" for k, v in cnt.most_common()]
    caps = sum(1 for p in prov for x in prov[p] if x[3])
    L += ["", f"Capitals among the new regions: {caps}; resource regions: {len(new) - caps}."]
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(OUT, len(new), "regions;", cnt.most_common())


if __name__ == "__main__":
    main()
