import numpy as np, merger_proto as M
v_ref, idx_ref, bb = M.read_mesh(0)
valid = M.global_validity_from_coverage(); L = M.lf_heights()
xs, ys, zs, flags, nrm, tris = M.build(0, 0, L, valid)
N=M.N; C=float(M.CELL)
print('validity rows 0..3, cols 0..24 (global):')
for J in range(4): print(''.join('#' if valid[J,I] else '.' for I in range(25)))
print('flags rows 0..3:')
for j in range(4): print(''.join(str(flags[j*N+i]) for i in range(25)))
out = M.merge(xs, ys, zs, flags, nrm, tris, np.float32(0.9999))
ours=set(q for t in out for q in t)
gi=np.round(v_ref[:,0]/C).astype(int); gj=np.round(v_ref[:,2]/C).astype(int)
ref=set(gj[q]*N+gi[q] for q in range(len(v_ref)) if v_ref[q,1]>-50)
print('survivors rows 0..6 vanilla / ours:')
for j in range(7): print(''.join('#' if j*N+i in ref else '.' for i in range(40)), '  ', ''.join('#' if j*N+i in ours else '.' for i in range(40)))
