<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TerryClone.Core\TerryClone.Core.csproj" />
    <ProjectReference Include="..\TerryClone.Formats\TerryClone.Formats.csproj" />
    <ProjectReference Include="..\TerryClone.Db\TerryClone.Db.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
