<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TerryClone.Core\TerryClone.Core.csproj" />
    <ProjectReference Include="..\TerryClone.Formats\TerryClone.Formats.csproj" />
    <ProjectReference Include="..\TerryClone.Db\TerryClone.Db.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="3.119.0" />
    <PackageReference Include="Vortice.D3DCompiler" Version="3.8.3" />
    <PackageReference Include="Vortice.Direct3D11" Version="3.8.3" />
    <PackageReference Include="Vortice.DXGI" Version="3.8.3" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>
